#!/bin/bash
# vim:ft=sh:
skip="-name modules -o -name completion -o -name \*.sw[opn] -o -name .gitmodules -o -name .git -o -name README.md -o -name dotdiff -o -name install"

if [ ${1:-nocp} = "cp" ]; then
  for file in `find . \( $skip \) -prune -o -type f -print`
  do
    orig=~/${file#*/}
    diff -q $orig $file &>/dev/null || cp $orig $file
  done

else
  (for file in `find . \( $skip \) -prune -o -type f -print`
  do
    diff -ub $file ~/${file##*/} 2>/dev/null
  done) | less -E -X
fi
