#!/bin/bash
find . \( -name modules -o -name .git -o -name completion \) -prune -o -name .[a-z]\* -print | cpio -dpm ~
cp -rp bin ~
cp rbenv/install/* /usr/local/share/ruby-build
cp modules/git-flow-completion/git-flow-completion.bash ~/.completion/
cp modules/completion-ruby/completion-* ~/.completion
cp modules/heroku_bash_completion/heroku_bash_completion.sh ~/.completion
cp completion/all ~/.completion/
