#!/bin/bash
set -x
find . \( -name modules -o -name .git -o -name completion \) -prune -o -name .[a-z]\* -print | cpio -dpm ~
cp -rp bin ~
if [ -d /etc/bash_completion.d ]; then
  sudo cp completion/postgresql /etc/bash_completion.d
else if [ -d /usr/local/etc/bash_completion.d ]; then
  cp completion/postgresql /usr/local/etc/bash_completion.d
fi

