debug_print("Application: " .. get_application_name())
debug_print("Window: " .. get_window_name());
-- set_window_workspace(2);
-- maximize();
-- string.match(get_window_name(), "LibreOffice Writer")
-- make_always_on_top();
--
-- Application: gjs
-- Window: @!0,0;BDHF
-- Application: gjs
-- Window: @!1920,0;BDHF
-- Application: Lock Screen — 1Password
-- Window: Lock Screen — 1Password
-- Application: devops-eng - D - 3 new items - Slack
-- Window: devops-eng - D - 3 new items - Slack
-- Application: Firefox
-- Window: Platforms (Client-facing)  — Mozilla Firefox
-- Application: Terminal
-- Window: philipchampon@pcpc: ~
-- Application: tilix
-- Window: Tilix: philipchampon@pcpc: ~
-- Application: Untitled window
-- Window: Untitled window
-- Application: gnome-session-properties
-- Window: Startup Applications Preferences
-- Application: New Tab - Brave
-- Window: New Tab - Brave
